# Generated by Django 4.2.7 on 2025-08-23 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('generation', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('guesses_count', models.IntegerField(default=0)),
                ('max_guesses', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokedex_number', models.IntegerField()),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('generation', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('base_stat_total', models.IntegerField()),
                ('is_legendary', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
                ('habitat', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['pokedex_number'],
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.gamesession')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pokemon')),
            ],
            options={
                'ordering': ['guess_number'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='target_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pokemon'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
