# Generated by Django 4.2.7 on 2025-08-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['pokedex_number'], 'verbose_name': 'Pokémon', 'verbose_name_plural': 'Pokémon'},
        ),
        migrations.AddField(
            model_name='gamesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.URLField(blank=True, help_text='Official artwork URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite_url',
            field=models.URLField(blank=True, help_text='Game sprite URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('game_session', 'pokemon')},
        ),
    ]
